server:
    port: ${SERVER_PORT:6543}
    address: ${SERVER_ADDR:localhost}

spring:
    application:
        name: TutorHubSpring

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: skhuzhaev
        password: ~!@#$%killerbee1998

    liquibase:
        enabled: true
        change-log: classpath:changelog/dbchangelog.xml

variables:
    HIBERNATE_VALUES:
        URL: ${URL:jdbc:postgresql://localhost:5432/postgres}
        USER: ${USER:skhuzhaev}
        PASSWORD: ${PASSWORD:~!@#$%killerbee1998}
        POOL_SIZE: ${POOL_SIZE:10}

    ENCRYPTION_VARIABLES:
        ITERATION_COUNT: ${ITERATION_COUNT:65536}
        ENCRYPTION_BYTE_SIZE: ${ENCRYPTION_BYTE_SIZE:128}
        ENCRYPTION_PARALLEL_NUMBER: ${ENCRYPTION_BYTE_SIZE:1}

        SECRET_KEY: ${SECRET_KEY:dYS/SPWOmETxjKq2G5slHh99PbpWayezXCvq0h+V0JA=}
        SECRET_DATE: ${SECRET_DATE:Wed Oct 30 17:51:23 UZT 2024}
        PROTOCOL_TYPE: ${PROTOCOL_TYPE:AES}
        SIGNATURE_PROTOCOL: ${SIGNATURE_PROTOCOL:SHA256withRSA}
        CIPHER_PROTOCOL_TYPE: ${CIPHER_PROTOCOL_TYPE:RSA/ECB/PKCS1Padding}
        MESSAGE_DIGEST_ALGORITHM: ${MESSAGE_DIGEST_ALGORITHM:SHA-256}
        KEY_PAIR_SIGNATURE_PROTOCOL: ${KEY_PAIR_SIGNATURE_PROTOCOL:RSA}
        KEY_PAIR_GENERATOR_PROTOCOL: ${KEY_PAIR_GENERATOR_PROTOCOL:DiffieHellman}
        SECRET_KEY_FACTORY_PROTOCOL: ${SECRET_KEY_FACTORY_PROTOCOL:PBKDF2WithHmacSHA1}
        CIPHER_PROTOCOL_TYPE_SYMMETRIC: ${CIPHER_PROTOCOL_TYPE_SYMMETRIC:PKCS5Padding}

    WEB_FLUX_PARAMS:
        RESULT_COUNT: ${RESULT_COUNT:1000}

    JWT_VARIABLES:
        ISSUER: ${ISSUER:GpsTabletsServiceApplication}
        SECRET: ${SECRET:rH2JRKHNANolgCdUqsxNKHOAOjaLH2Z4bLyr3lS3ucCJo3q558Nicl8Ksi3fl69GZWC3HuwTX7KDBQQZecqkw==}

    KAFKA_VARIABLES:
        KAFKA_BROKER : ${KAFKA_BROKER:localhost:9092}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:SSD.GPS.TABLETS_DEV_TEST}
        COMPRESSION_TYPE_CONFIG: ${COMPRESSION_TYPE_CONFIG:lz4}

        RETRIES_CONFIG : ${RETRIES_CONFIG:3}
        LINGER_MS_CONFIG : ${LINGER_MS_CONFIG:50}
        KAFKA_ACKS_CONFIG : ${KAFKA_ACKS_CONFIG:all}
        BATCH_SIZE_CONFIG : ${BATCH_SIZE_CONFIG:16384}
        BUFFER_MEMORY_CONFIG : ${BUFFER_MEMORY_CONFIG:33554432}
        REQUEST_TIMEOUT_MS_CONFIG : ${REQUEST_TIMEOUT_MS_CONFIG:30000}
        TRANSACTION_TIMEOUT_CONFIG : ${TRANSACTION_TIMEOUT_CONFIG:8}
        KAFKA_SENDER_MAX_IN_FLIGHT : ${KAFKA_SENDER_MAX_IN_FLIGHT:1024}
        MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION : ${MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION:3}

        KAFKA_TOPICS:
            SOS_TOPIC: ${SOS_TOPIC:SOS_TOPIC_DEV}
            ACTIVE_TASK: ${ACTIVE_TASK:active_task_dev}
            NOTIFICATION: ${NOTIFICATION:notification_dev}
            CAR_TOTAL_DATA: ${CAR_TOTAL_DATA:car_total_data_dev}
            SOS_TOPIC_FOR_ANDROID_NOTIFICATION: ${SOS_TOPIC_FOR_ANDROID_NOTIFICATION:SOS_TOPIC_FOR_ANDROID_NOTIFICATION_DEV}
